#!/data/adb/magisk/busybox sh

{
configuration="$(cat /data/adb/modules/brightness-fix/.tmp)"

if pgrep -x "led" > /dev/null; then
    kill -STOP $(pgrep -f led)
else
sleep 1
fi

# default val
if [ -z "$(cat /data/adb/modules/brightness-fix/.tmp)" ]; then
    echo "2047" > "/data/adb/modules/brightness-fix/.tmp"
fi

# main
while true; do
    if [ ! "$(cat /sys/class/leds/lcd-backlight/brightness)" = "$configuration" ]; then
        echo "$configuration" > "/sys/class/leds/lcd-backlight/brightness"
        sleep 1
    fi 
done
} > /dev/null 2>&1
