#!/bin/sh
{
configuration_value="$(cat /data/adb/modules/brightness-fix/.tmp)"
configuration_file="/data/adb/modules/brightness-fix/.tmp"

if pgrep -x "led" >/dev/null 2>&1; then
kill -STOP $(pgrep -x led)
fi

if [ -z "$configuration_value" ]; then 
echo "2047" > "$configuration_file"
fi


# MAIN SCRIPT
while true; do
    if [ "$(cat /sys/class/leds/lcd-backlight/brightness)" != "$configuration_value" ]; then
        echo "$configuration_value" > "/sys/class/leds/lcd-backlight/brightness"
        sleep 1
    fi 
done
} > /dev/null 2>&1
